### ISSUE TITLE
Modbus-Read node stops requesting data

### ISSUE THREAD

**Issue by FrankX0** [BiancoRoyal/node-red-contrib-modbus#369]
### Which node-red-contrib-modbus version are you using?

5.25.0

### What happened?

I am using FC 3 to read every 10 seconds 40 registers from a SolarEdge inverter.
Every now and then the node stops producing output. The status is then always still active.
If I manually trigger the node the inverter responds as expected.
Sometimes the node continues reading every 10 seconds.
If it does not, I need to redeploy the flow.
Sometimes this does not restart the node, then I even have to restart Node-RED.

How do I start debugging this?
Any help is appreciated.

### Server

Other/External server

### How can this be reproduced?

[flow.zip](https://github.com/BiancoRoyal/node-red-contrib-modbus/files/10725809/flow.zip)

**Comment by biancode** [comment]
**Follow-up (stale-closed) — please verify on `node-red-contrib-modbus@5.46.0` (npm)**

This issue was closed by the stale bot without a verified fix. Client **FSM / reconnect / recovery** hardening in [v5.46.0](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md) is intended to address this symptom class (silent stall, stuck `init`/`failed`/`broken`, reconnect after outage).

Please upgrade and field-test:

```bash
npm i node-red-contrib-modbus@5.46.0
```

Then reply with ✅ **fixed** / ❌ **still broken** (NR + Node.js versions + short state log), **reopen** this issue, or open a **new** issue if something else shows up. Reporter confirmation is the real close criterion.
