### ISSUE TITLE
modbus node error.

### ISSUE THREAD

**Issue by colin0031** [BiancoRoyal/node-red-contrib-modbus#419]
### Which node-red-contrib-modbus version are you using?

5.26

### What happened?

**My usecase**
I am using node red and modbus node for communication between mobile robots and Automatic gates.
When a robot is near the door it should open automatically. I am using modbus node to activate a relay in MOXA box.

**Issue**
The problem is weird, When Robot sends a boolean value to modbus write node and the modbus write node doesn't receive it at the first time and a second push is necessary for modbus node to activate/deactivate the relay.
I have tried it manually also using inject node. 90 percent time it receives but sometimes signal is being lost.

### Server

Modbus-Server Node

### How can this be reproduced?

create an inject node in node red and a modbus(modbus node should be connected to an IO device- I use moxa)

Try injecting boolean: true/false to modbus node. switch between true and false for 20 times and you will see at least some signals are being lost.
![modbuss](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/136078880/248efe03-7d6a-4006-9032-0256ac834b02)

### What did you expect to happen?

More testing required

### Other Information

..

**Comment by biancode** [comment]
**Follow-up (stale-closed) — please verify on `node-red-contrib-modbus@5.46.0` (npm)**

This issue was closed by the stale bot without a verified fix. Client **FSM / reconnect / recovery** hardening in [v5.46.0](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md) is intended to address this symptom class (silent stall, stuck `init`/`failed`/`broken`, reconnect after outage).

Please upgrade and field-test:

```bash
npm i node-red-contrib-modbus@5.46.0
```

Then reply with ✅ **fixed** / ❌ **still broken** (NR + Node.js versions + short state log), **reopen** this issue, or open a **new** issue if something else shows up. Reporter confirmation is the real close criterion.
