### ISSUE TITLE
Disabling one Modbus Flex Getter stops all from working

### ISSUE THREAD

**Issue by hoegge** [BiancoRoyal/node-red-contrib-modbus#423]
### Which node-red-contrib-modbus version are you using?

5.23.3

### What happened?

I have a flow with more than one Modbus flex getter and a couple of sequencers. For testing I had a separat node "Modbus Flex Getter". When done testing I disabled that node. This results in all Modbus nodes to stop functioning. It seems like the node instances share (too much) state, so the are not independent, which I assume is a bug / or at least not desirable to have too many "hidden" connections between nodes.

### Server

Other/External server

### How can this be reproduced?

Create a flow with more Modbus Getters. Disable one of them and observe all data retrieval stops.

**Comment by hoegge** [comment]
> Hi @hoegge, this is controlled by Node-RED itself, we can check this, but in the architecture the node uses a client as expected in Node-RED and they are coupled via NodeJS events only from my perspective. If you disable and this disables the client, which is used at all nodes, ...

Not sure I understand @biancode . Does disabling a flex getter disable "the client" which is what? I have multiple flex getters, and if I disable one then the others are also disabled.

**Comment by biancode** [comment]
**Follow-up (stale-closed) — please verify on `node-red-contrib-modbus@5.46.0` (npm)**

Related to shared-client behaviour when disabling one consumer (also #487). v5.46.0 includes FSM close/reconnect hardening that may reduce collateral “all nodes closed” effects when one Flex-Getter is disabled ([CHANGELOG](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md)).

```bash
npm i node-red-contrib-modbus@5.46.0
```

Please re-test disable-one-node scenarios and reply ✅ / ❌, **reopen**, or open a **new** issue. (Some of this is still Node-RED shared-config semantics.)

**Comment by unclej84** [comment]
❌ still broken

- I just fried it by copying a Modbus Flex Getter and deployed -> both are connected
- Disabled the copied Flex Getter -> Original Flex Getter got closed
- Re-Enabled copied Flex Getter -> Both got connected again
- Deleted copied Flex Getter -> Original one got closed

All other Flex Getters woth different Servers stayed connected

**Comment by biancode** [comment]
❌ confirmed — root cause found and fixed in `src/` on the current development line (package **5.50.0** WIP).

### What was wrong
1. `registerForModbus(node)` stored consumers under the object key `"[object Object]"`, so multiple Flex-Getters on one client were **not** tracked separately.
2. On disable/delete of one consumer, the client still sent FSM **`STOP`** even when siblings remained → all nodes on that client closed.

### Fix (spec `shared-client-deregister-isolation`)
- Registry keys are always **node id strings** (accepts node object or id).
- Deregister while siblings remain → **no STOP**, connection stays up.
- Deregister of the **last** consumer → close/stop as before.

### How to verify (after you pull / link this build)
1. Two Modbus-Flex-Getter on the **same** Modbus-Client → both connected.
2. Disable or delete one → the other must **stay** connected/active.
3. Disable/delete the last one → client stops.

Please re-test and reply ✅ / ❌. Related: #487.

**Comment by unclej84** [comment]
✅ fixed - at least for me. Thanks for all the efforts

- Copying node worked
- disabling node worked without affecting other nodes
- re-enabling node worked without affecting other nodes
- deleting node worked without affecting other nodes
Could not test to delete all/the last node
