### ISSUE TITLE
"FSM failed" is not under normal condition for me - with that message it has a failure

### ISSUE THREAD

**Issue by mjmokhtar** [BiancoRoyal/node-red-contrib-modbus#467]
### Which node-red-contrib-modbus version are you using?

5.31.0

### What happened?

"FSM failed" is not under normal condition for me - with that message it has a failure

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/108962994/b3015a7a-45b1-4015-80a6-0b78b9c7287d)

### Server

Modbus-Server Node

### How can this be reproduced?

need your help to fix it

### What did you expect to happen?

node warning doesn't appear anymore again

### Other Information

Previously I tried to make a modbus program using npm using a code script, and succeeded in reading the data, but it had an impact on the modbus read palette

**Comment by biancode** [comment]
Hi, also here. It needs much more information and not just like "doesn't work". Please, follow the issue template to provide information, otherwise we can not reproduce that issue you had and can not help you.

**Comment by biancode** [comment]
**Follow-up (stale-closed) — please verify on `node-red-contrib-modbus@5.46.0` (npm)**

This issue was closed by the stale bot without a verified fix. Client **FSM / reconnect / recovery** hardening in [v5.46.0](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md) is intended to address this symptom class (silent stall, stuck `init`/`failed`/`broken`, reconnect after outage).

Please upgrade and field-test:

```bash
npm i node-red-contrib-modbus@5.46.0
```

Then reply with ✅ **fixed** / ❌ **still broken** (NR + Node.js versions + short state log), **reopen** this issue, or open a **new** issue if something else shows up. Reporter confirmation is the real close criterion.
