### ISSUE TITLE
Segmentation fault (core dumped) when configuring Modbus in Node-RED Docker

### ISSUE THREAD

**Issue by mariacomsa** [BiancoRoyal/node-red-contrib-modbus#468]
### Which node-red-contrib-modbus version are you using?

5.31.0

### What happened?

I am using Node-RED with Docker. When I configure the node-red-contrib-modbus module, a segmentation fault error occurs. The error message is as follows:
![Captura](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/163829949/767d18b2-e22c-4c7e-8821-6fe61a4f7d30)
This issue can be resolved by running npm run rebuild inside the Docker volume at data/node_modules/@serialport/bindings-cpp.

### Server

Modbus-Server Node

### How can this be reproduced?

1. Use Node-RED with Docker.
2. Install node-red-contrib-modbus version 5.31.0.
3. Configure the Modbus settings.
4. Observe the segmentation fault error as shown in the attached screenshot.
5. Disable the flow or node that uses the node-red-contrib-modbus library by editing the flows.json file to allow the container to restart.
6. After the container restarts, run npm run rebuild in the Docker volume at data/node_modules/@serialport/bindings-cpp.
7. Re-enable the flow or node and verify the configuration.

### What did you expect to happen?

I expected the Modbus configuration to work without causing a segmentation fault error. Ideally, there should be no need to manually rebuild the @serialport/bindings-cpp module inside the Docker volume

**Comment by core-tinkerer** [comment]
Hello all,

same segfault here. Running:

- Raspberry v3
- Docker v27.0.3
- containerized Node-Red v4.0.2
- node-red-contrib-modbus v5.40.0.

Raspi has a FTDI-based smartmeter irda reader on ttyUSB0 which is working fine using node-red-contrib-smartmeter v0.6.3 (which also uses serialport) .
ttyUSB1 is a FTDI-based modbus/RS485-to-usb dongle which has been working on a very old non-docker install (different SD card, same raspi, see versions at the end, both setups available for tests).

In the log below log I first used the dongle on ttyUSB1 with the node-red-node-serialport v2.0.2 to verify the pass-through is working while a deactivated modbus config node on same port was present (in parallel the smartmeter on ttyUSB0 was sending valid data).  Then I deleted the serialport config node, deployed the workflows, then activated the modbus config node, deployed again, and got a segfault.

I also applied npm run rebuild on data/node_modules/@serialport/bindings-cpp and since this didn't work I also tried to rebuild bindings which also had no effect.

Docker cmd:
`docker run -it -p 1880:1880 -v /srv/docker/nodered-scada:/data --name $CONTAINERNAME --group-add dialout --device=/dev/ttyUSB0 --device=/dev/ttyUSB1 nodered/node-red`

Console log of container:
```
Using default tag: latest
latest: Pulling from nodered/node-red
Digest: sha256:fa8fbcf2ddc1e1b2cdea3c1e6d027413f583956fc499289c432650a3ea03c10b
Status: Image is up to date for nodered/node-red:latest
docker.io/nodered/node-red:latest
nodered-scada
nodered-scada
22 Jul 15:46:38 - [info] 

Welcome to Node-RED


22 Jul 15:46:38 - [info] Node-RED version: v4.0.2
22 Jul 15:46:38 - [info] Node.js  version: v20.15.1
22 Jul 15:46:38 - [info] Linux 6.6.31+rpt-rpi-v8 arm64 LE
22 Jul 15:46:39 - [info] Loading palette nodes
22 Jul 15:46:43 - [info] Dashboard version 3.6.5 started at /ui
22 Jul 15:46:44 - [info] Settings file  : /data/settings.js
22 Jul 15:46:44 - [info] Context store  : 'default' [module=localfilesystem]
22 Jul 15:46:44 - [info] User directory : /data
22 Jul 15:46:44 - [warn] Projects disabled : editorTheme.projects.enabled=false
22 Jul 15:46:44 - [info] Flows file     : /data/flows.json
22 Jul 15:46:44 - [info] Server now running at http://127.0.0.1:1880/
22 Jul 15:46:45 - [info] Starting flows
22 Jul 15:46:45 - [info] Started flows
22 Jul 15:46:45 - [info] [serialconfig:d43ebb392202afb7] serial port /dev/ttyUSB1 opened at 9600 baud 8E1
22 Jul 15:46:45 - [info] [mqtt-broker:Mosquitto ] Connected to broker: mqtt://192.168.1.1:1883
22 Jul 15:51:56 - [info] Stopping flows
22 Jul 15:51:56 - [info] serial port /dev/ttyUSB1 closed
22 Jul 15:51:56 - [info] [mqtt-broker:Mosquitto ] Disconnected from broker: mqtt://192.168.1.1:1883
22 Jul 15:51:56 - [info] Stopped flows
22 Jul 15:51:56 - [info] Updated flows
22 Jul 15:51:56 - [info] Starting flows
22 Jul 15:51:56 - [info] Started flows
22 Jul 15:51:57 - [info] [mqtt-broker:Mosquitto ] Connected to broker: mqtt://192.168.16.1:1883
22 Jul 15:52:19 - [info] Stopping flows
22 Jul 15:52:19 - [info] [mqtt-broker:Mosquitto ] Disconnected from broker: mqtt://192.168.16.1:1883
22 Jul 15:52:19 - [info] Stopped flows
22 Jul 15:52:19 - [info] Updated flows
22 Jul 15:52:19 - [info] Starting flows
22 Jul 15:52:20 - [info] Started flows
22 Jul 15:52:20 - [info] [mqtt-broker:Mosquitto ] Connected to broker: mqtt://192.168.1.1:1883
./entrypoint.sh: line 14:     7 Segmentation fault      (core dumped) /usr/local/bin/node $NODE_OPTIONS node_modules/node-red/red.js --userDir /data $FLOWS "${@}"
```
Appears as soon contrib-modbus tries to do something with the serial port the segfault happens...

For completness, the old working install was:
- Same Raspberry v3
- Raspbian/Debian 11.10
- nodejs v12.22.12
- Node-Red v2.1.3
- node-red-contrib-modbus v5.14.1

Happy to take advise, provide more logs, do more tests, ...
Also happy to see  a workaround.

Thank you!

**Comment by core-tinkerer** [comment]
Some more tries later:

Manual downgrade of contrib-modbus in container to 5.28 ad 5.22 did not help and end in segfaults.

A plain fresh installed setup works fine:
- Raspberry v3
- NO Docker 
- NodeJS v20.15.1
- Node-Red v4.0.2
- node-red-contrib-modbus v5.40.0.

Although this now will be my workaround, I really would like to run this setup in a container for easier maintenance.

Still have all SD cards at hand if someone needs help at bug hunting...
